CHANGELOG.md, CONTRIBUTING.md, README.md, setup.cfg, src/sarif/__main__.py, src/sarif/cmdline/main.py, src/sarif/operations/blame_op.py, src/sarif/operations/csv_op.py, src/sarif/operations/diff_op.py, src/sarif/operations/html_op.py, src/sarif/operations/ls_op.py, src/sarif/operations/summary_op.py, src/sarif/operations/templates/sarif_summary.html, src/sarif/operations/trend_op.py, src/sarif/operations/word_op.py, src/sarif/sarif_file.py
Add the `--blame-filter` option to all the commands for which it makes sense.  It takes a path to a filter-file and filters the results according the the author_mail from the git blame information.
=> Add blame filter

sarif/sarif_file.py
In some cases message doesn't have "text" attribute and result_to_record call fails with exception:
File "C:\Python\lib\site-packages\sarif\sarif_file.py", line 550, in result_to_record
message = result["message"]["text"]
KeyError: 'text'
Example - binskim scan results from Defender for DevOps
Per RFC3629 At least one of the text (§3.11.8) or id (§3.11.10) properties SHALL be present https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#RFC3629 Proposed change checks if message have text or id attribute and use corresponding key to get message.
Sample sarif data:
{
"ruleId": "BA2015",
"ruleIndex": 2,
"level": "error",
"message": {
"id": "Error_NoHighEntropyVA",
"arguments": [
"clipboard_x86_64.exe"
]
},
=> Add getting message in cases where "text" property is not presented in sarif file per RFC3629

sarif/loader.py
The documentation states:
> The file_or_dir specifier can include wildcards e.g. c:\temp\**\devskim*.sarif (i.e. a "glob").
However it does not currently enable the use of ** when using glob. This PR adds recursive = True to enable it.
=> Add recursive = True to glob

sarif/cmdline/main.py, sarif/operations/emacs_op.py, sarif/operations/templates/sarif_emacs.txt
Introduce new 'emacs' sub-command (derived from html command) that converts SARIF to a text file. When opened in emacs, this file will bring a compilation mode, allowing easy navigation among code scan issues.
=> New tool that converts SARIF file to txt suitable for Emacs

README.md, sarif/loader.py, sarif/operations/diff_op.py, sarif/operations/html_op.py, sarif/sarif_file.py
Closes https://github.com/microsoft/sarif-tools/issues/18
Diff output now includes locations for (possibly new) occurrences of issues.
Note that this is a breaking change to the diff json output, but hopefully a good one.  We'll call the next version 2.0 as a result.
=> Fix #18 - show locations of new issue occurrences

README.md, sarif/cmdline/main.py, sarif/operations/codeclimate_op.py
Implemented a new command `sarif codeclimate` to generate output for GitLab Code Quality report.
GitLab uses Code Climate tool for static analysis and a published report is shown in Merge Request UI as a Code Quality report. 
GitLab also provides a way to upload a report generated by custom tool - see https://docs.gitlab.com/ee/ci/testing/code_quality.html#implement-a-custom-tool
Many SAST tools generates SARIF files, so to use them in GitLab they must be converted to Code Climate format which is pretty simple:
```json
[
{
"description": "'unused' is assigned a value but never used.",
"check_name": "no-unused-vars",
"fingerprint": "7815696ecbf1c96e6894b779456d330e",
"severity": "minor",
"location": {
"path": "lib/index.js",
"lines": {
"begin": 42
}
}
}
]
```
=> Convert SARIF files to GitLab (Code Climate) format

.gitignore, README.md, poetry.lock, pyproject.toml, sarif/cmdline/main.py, sarif/filter/filter_stats.py, sarif/filter/general_filter.py, sarif/operations/codeclimate_op.py, sarif/sarif_file.py, tests/test_general_filter.py
**BREAKING CHANGE**
Fixes #13 
Implemented general filtering for any field in a results object. This replaces blame filtering which filtered only by author emails in blame details.
The filter format is switched from plain text to YAML.
Here is an example of a filter file (from updated README.md):
```yaml
description: Example filter from README.md
include:
- author-mail: "@microsoft.com"
locations[*].physicalLocation.artifactLocation.uri: "*.java"
- committer-mail: "/^<myname.*\\.com>$/"
exclude:
- location: "Test*.java"
- suppression:
```
Field names must be specified as a JSONPath expression, substrings and Regex are supported as before.
The following shortcuts are supported (from updated README.md):
| Shortcut | Full JSONPath |
| -------- | -------- |
| author | properties.blame.author …
=> Implemented general filtering (replaces blame filtering)

poetry.lock, pyproject.toml
Resolves https://github.com/microsoft/sarif-tools/security/dependabot/3
Updated `pytest` to `>7.2.0' (7.4.2) which doesn't include vulnerable 'py' library.
```
> poetry update
Updating dependencies
Resolving dependencies... (1.1s)
Package operations: 2 installs, 2 updates, 4 removals
• Removing attrs (23.1.0)
• Removing more-itertools (10.1.0)
• Removing py (1.11.0)
• Removing wcwidth (0.2.8)
• Installing exceptiongroup (1.1.3)
• Installing iniconfig (2.0.0)
• Updating pluggy (0.13.1 -> 1.3.0)
• Updating pytest (5.4.3 -> 7.4.2)
```
=> Update pytest to >7.2.0 without vulnerable py dep

sarif/filter/general_filter.py, tests/test_general_filter.py
Fixes #33.
When there are no inclusion filter `included_stats` is not initialised to a proper value. Set the default value as `included`.
Added a test case to cover
=> Fixed error when there are no inclusion filters.

README.md, sarif/cmdline/main.py, sarif/filter/filter_stats.py, sarif/filter/general_filter.py, sarif/loader.py, sarif/operations/diff_op.py, sarif/operations/upgrade_filter_op.py, sarif/sarif_file.py, sarif/sarif_file_utils.py, tests/test_general_filter.py, tests/test_version.py
Add an operation to upgrade old blame filters to new general YAML filters
As part of testing this, I remembered why we had the old "unconvincing line number" condition applied to the filtering.  The reason is that some static analysis tools record line number `"1"` for whole-file issues, but it's wrong to apply blame filtering based on who changed line number 1.  I've reinstated this using the new configuration framework, defaulting to true.
Fixes #31
=> Add blame filter upgrade operation

CHANGELOG.md, README.md, poetry.lock, pyproject.toml, sarif/operations/upgrade_filter_op.py, sarif/sarif_file.py
Getting release v2.0.0 ready.
Checked `black`, `pylint`, `pytest`.
Ran `poetry upgrade` to get latest dependencies.
Ran each command once as a sanity check (and fixed a regression :-p).
Pushed to test.pypi.org and installed and ran from there.
=> Prepare release v2.0.0

tests/test_version.py
Hi :)
While packaging sarif-tools for NixOS, I noticed the `test_version` test fails because it expects `1.0.0` while the current version is `2.0.0`. Here's an update for the test.
```
============================= test session starts ==============================
platform linux -- Python 3.11.6, pytest-7.4.3, pluggy-1.3.0
rootdir: /build/source
collected 30 items                                                             
tests/test_general_filter.py .............................               [ 96%]
tests/test_version.py F                                                  [100%]
=================================== FAILURES ===================================
_________________________________ test_version _________________________________
def test_version():
>       assert …
```
=> Fix test_version test

CHANGELOG.md, sarif/operations/copy_op.py
The spec states "invocation" is an object, not a string: https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790817
This broke some parsing by other tools/libs.
=> Make "invocation" an object per spec

sarif/sarif_file_utils.py, tests/test_sarif_file_utils.py
Add defensive code to avoid trying to run word wrap when there is not enough space on the line due to long issue code.  Also added unit test for this function `combine_code_and_description` that reproduced the issue.
Fixes #51
=> Avoid word wrap crash when issue code long

CHANGELOG.md, sarif/operations/blame_op.py
`git blame` doesn't recognise `file://` URIs as paths inside the repository, so sarif-tools needs to turn them into normal file paths.  This change makes the `sarif blame` command do that, using the stdlib [url2pathname](https://docs.python.org/3/library/urllib.request.html#urllib.request.url2pathname) API.
Fixes #53
=> Sanitise file URIs for git blame

azure-pipelines/release.yml
To enable testing of the new AzDO-based release pipeline, I added an empty `release.yml` a while back. The presence of the file was necessary to create the pipeline. However, it is currently running against all PRs, whereas it is intended to only run when kicked off manually or perhaps based on tag creation.
This PR adds a minimal chunk of YAML to prevent the pipeline from running in PRs. The `pr: none` at the top is the relevant bit. `trigger: none` tells it to not run on commits in main (CI) either. And the simple stages are required because all pipelines must have at least one stage, one job, and one step.
=> Prevent Sarif-Tools-Release pipeline from running on PRs

CHANGELOG.md, README.md, sarif/cmdline/main.py, sarif/issues_report.py, sarif/operations/diff_op.py, sarif/sarif_file.py, sarif/sarif_file_utils.py, tests/test_diff_op.py
v3.0.0 introduced the new `IssuesReport` class to consolidate summarisation logic that had been scattered across multiple operations.  However, we missed updating the `diff` command accordingly, so it broke.
I've also improved the documentation to describe `IssuesReport` and added a unit test that would have detected the regression.
Fixes #58
=> Fix regression in diff command

.github/workflows/build.yml, .github/workflows/validation.yml
Added GitHub Actions to validate PRs. Failures in these actions will block the PR:
- `build.yml` -- Just does a normal build and uploads the resulting wheel as a build asset.
- `validation.yml` -- Runs tests and also does a hygiene check. I'd suggest running `ruff` or `black` during hygiene eventually, but currently it just verifies that the `poetry.lock` file is up-to-date.
=> Add GitHub Actions for PR validation

.github/workflows/build.yml, .github/workflows/validation.yml
Noticed these warnings after the initial runs of `validation.yml`. Upgrading to the latest version (v4) should resolve them.
=> Upgrade GitHub Actions to actions/checkout@v4

sarif/sarif_file.py, sarif/sarif_file_utils.py, tests/test_sarif_file_utils.py
Fix https://github.com/microsoft/sarif-tools/issues/43
Previously a result's "level" was simply `result.level` or `"warning"` if the result did not specify a level.
This PR updates our level calculation logic to match the rules described in [the SARIF docs](https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html#_Toc141790898). The precedence order is:
1. `result.level` if present
2. `"none"` if the `result.kind` is not `"fail"`
3. The invocation's override for `level` if present
4. The `level` from the rule's `defaultConfiguration` if present
5. Fall back to `"warning"`
=> Improve logic for calculating result level

sarif/cmdline/main.py, sarif/sarif_file.py, tests/test_check_switch.py
Fix #73 
Fixed regression that happened with the introduction of `IssuesReport`. The code that handles `--check` was still trying to call the old `get_result_count_by_severity` API.
- Fixed by using `IssuesReport.get_issue_count_for_severity()` instead. 
- Removed dead `SarifFile.get_result_count_by_severity` code
- Added unit test.
=> Fix crash when using `--check` switch

sarif/operations/csv_op.py, sarif/operations/trend_op.py
Fix #82 
For some baffling reason, the `csv` module [defaults to `\r\n` line endings](https://docs.python.org/3.11/library/csv.html#csv.Dialect.lineterminator). When paired with stdlib's default behavior of [translating `\n` to the system default line ending](https://docs.python.org/3.11/library/functions.html#open) this resulted in `\r\r\n` on Windows machines. 
Our first attempt to fix this, back during the Hackathon, was to set `newline=""` on the `open` call. That does result in correct line endings on Windows. But since `csv` defaults to `\r\n` we still end up getting incorrect line endings on Linux.
Fixed by reverting to the default behavior of `open` and telling `csv.DictWriter` to use `\n` as the line terminator.
This is covered by the unit tests I'm about to add in …
=> Fix line terminators in generated CSV files

CONTRIBUTING.md, README.md, sarif/operations/html_op.py, sarif/operations/templates/sarif_summary.html, sarif/sarif_file.py, tests/ops/html/test_html.py
Implementing enhancement request #76 
When generating the HTML report, it looks up the `helpUri` (using some new APIs to get rule by code) and adds a clickable link to the documentation of the rule.
While doing this, I've made some slight tweaks:
- `html_test` is now more forgiving of whitespace
- Some wording in README.md
=> Add helpUri to HTML report (#76)

sarif/operations/blame_op.py, tests/ops/blame/test_blame.py
=> Replace bad UTF-8 bytes when parsing git blame
